#!/bin/bash
# Copyright 2020 The MediaPipe Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# =========================================================================
#
# Script to build/run all MediaPipe desktop example apps (with webcam input).
#
# To build and run all apps and store them in out_dir:
#   $ ./build_desktop_examples.sh -d out_dir
#   Omitting -d and the associated directory saves all generated apps in the
#   current directory.
# To build all apps and store them in out_dir:
#   $ ./build_desktop_examples.sh -d out_dir -b
#   Omitting -d and the associated directory saves all generated apps in the
#   current directory.
# To run all apps already stored in out_dir:
#   $ ./build_desktop_examples.sh -d out_dir -r
#   Omitting -d and the associated directory assumes all apps are in the current
#   directory.

set -e

out_dir="."
app_dir="mediapipe/examples/qnx"
bin_dir="bazel-bin"

python_toolchain="python"
python_qnx_toolchain="python_qnx"
cpp_qnx_toolchain="cpp_qnx"
buildbase_qnx_toolchain="buildbase_qnx"

function clean() {
    echo "Running clean function."
    rm -rf $python_toolchain
    rm -rf $python_qnx_toolchain
    rm -rf $cpp_qnx_toolchain
    rm -rf $buildbase_qnx_toolchain
}

# Create toolchains.
if [ ! -d "$python_toolchain" ]; then
  mkdir -p "$python_toolchain"
  cat << EOF > "$python_toolchain/BUILD.bazel"
# Generated by python/private/toolchains_repo.bzl
package(default_visibility = ["//visibility:public"])

config_setting(
    name = "qnx",
    constraint_values = ["@platforms//os:qnx"],
)

exports_files(["defs.bzl"])
alias(name = "files",           actual = "@python_qnx//:files")
alias(name = "includes",        actual = "@python_qnx//:includes")
alias(name = "libpython",       actual = "@python_qnx//:libpython")
alias(name = "py3_runtime",     actual = "@python_qnx//:py3_runtime")
alias(name = "python_headers",  actual = "@python_qnx//:python_headers")
alias(name = "python_runtimes", actual = "@python_qnx//:python_runtimes")
alias(name = "python3",         actual = "@python_qnx//:bin/python3")
alias(name = "pip",             actual = "@python_qnx//:python_runtimes")
  EOF
  cat << EOF > "$python_toolchain/defs.bzl"
# Generated by python/private/toolchains_repo.bzl

load(
    "@rules_python//python/config_settings:transition.bzl",
    _py_binary = "py_binary",
    _py_test = "py_test",
)
load(
    "@rules_python//python/entry_points:py_console_script_binary.bzl",
    _py_console_script_binary = "py_console_script_binary",
)
load("@rules_python//python:pip.bzl", _compile_pip_requirements = "compile_pip_requirements")

host_platform = "qnx"
interpreter = "@python_qnx//:bin/python3"

def py_binary(name, **kwargs):
    return _py_binary(
        name = name,
        python_version = "3.14.0",
        **kwargs
    )

def py_console_script_binary(name, **kwargs):
    return _py_console_script_binary(
        name = name,
        binary_rule = py_binary,
        **kwargs
    )

def py_test(name, **kwargs):
    return _py_test(
        name = name,
        python_version = "3.14.0",
        **kwargs
    )

def compile_pip_requirements(name, **kwargs):
    return _compile_pip_requirements(
        name = name,
        py_binary = py_binary,
        py_test = py_test,
        **kwargs
    )

  EOF
  cat << EOF > "$python_toolchain/WORKSPACE"
# DO NOT EDIT: automatically generated WORKSPACE file for toolchain_aliases rule
workspace(name = "python")
  EOF

    ln -s /usr/bin $python_toolchain/bin
    mkdir $python_toolchain/include
    ln -s /usr/include/python3.14 $python_toolchain/include/python3.14
    mkdir $python_toolchain/lib
    ln -s /usr/lib/python3.14 $python_toolchain/lib/python3.14
    ln -s /usr/lib/libpython3.so $python_toolchain/lib/libpython3.so
    ln -s /usr/lib/libpython3.14.so $python_toolchain/lib/libpython3.14.so
    ln -s $python_toolchain/bin/python3 $python_toolchain/python
fi

if [ ! -d "$python_qnx_toolchain" ]; then
  mkdir -p "$python_qnx_toolchain"
  cat << EOF > "$python_qnx_toolchain/BUILD.bazel"
# Generated by python/repositories.bzl

load("@bazel_tools//tools/python:toolchain.bzl", "py_runtime_pair")
load("@rules_python//python/cc:py_cc_toolchain.bzl", "py_cc_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "files",
    srcs = glob(
        include = ["bin/**", "extensions/**", "include/**", "lib/**", "libs/**", "share/**"],
        # Platform-agnostic filegroup can't match on all patterns.
        allow_empty = True,
        exclude = ["**/* *", "lib/libpython3.14.so", "lib/**/*.a", "lib/python3.14/**/test/**", "lib/python3.14/**/tests/**", "**/__pycache__/*.pyc", "**/__pycache__/*.pyc.*", "**/__pycache__/*.pyo"],
    ),
)

cc_import(
    name = "interface",
    interface_library = "libs/python312.lib",
    system_provided = True,
)

filegroup(
    name = "includes",
    srcs = glob(["include/**/*.h"]),
)

cc_library(
    name = "python_headers",
    deps = select({
        "@bazel_tools//src/conditions:windows": [":interface"],
        "//conditions:default": None,
    }),
    hdrs = [":includes"],
    includes = [
        "include",
        "include/python3.14",
    ],
)

cc_library(
    name = "libpython",
    hdrs = [":includes"],
    srcs = select({
        "@platforms//os:windows": ["python3.dll", "libs/python312.lib"],
        "@platforms//os:macos": ["lib/libpython3.12.dylib"],
        "@platforms//os:linux": ["lib/libpython3.12.so", "lib/libpython3.12.so.1.0"],
        "@platforms//os:qnx": ["lib/libpython3.so", "lib/libpython3.14.so"],
    }),
)

exports_files(["python", "bin/python3"])

# Used to only download coverage toolchain when the coverage is collected by
# bazel.
config_setting(
    name = "coverage_enabled",
    values = {"collect_code_coverage": "true"},
    visibility = ["//visibility:private"],
)

py_runtime(
    name = "py3_runtime",
    files = [":files"],
    # coverage_tool attribute not supported by this Bazel version
    interpreter = "bin/python3",
    python_version = "PY3",
)

py_runtime_pair(
    name = "python_runtimes",
    py2_runtime = None,
    py3_runtime = ":py3_runtime",
)

py_cc_toolchain(
    name = "py_cc_toolchain",
    headers = ":python_headers",
    libs = ":libpython",
    python_version = "3.14",
)

# Hack our own toolchains here using python_runtimes.
toolchain(
    name = "qnx_py_toolchain",
    toolchain = ":python_runtimes",
    toolchain_type = "@rules_python//python:toolchain_type",
)

# We also need to resolve this for bazel_tools, otherwise it will pickup another
# rule and chaos will ensue.
toolchain(
    name = "qnx_py_toolchain2",
    toolchain = ":python_runtimes",
    toolchain_type = "@bazel_tools//tools/python:toolchain_type",
)

toolchain(
    name = "qnx_py_cc_toolchain",
    toolchain = ":py_cc_toolchain",
    toolchain_type = "@rules_python//python/cc:toolchain_type",
)
  EOF
  cat << EOF > "$python_qnx_toolchain/WORKSPACE"
# DO NOT EDIT: automatically generated WORKSPACE file for python_repository rule
workspace(name = "python_qnx")
  EOF
fi

if [ ! -d "$cpp_qnx_toolchain" ]; then
  mkdir -p "$cpp_qnx_toolchain"
  cat << EOF > "$cpp_qnx_toolchain/BUILD.bazel"
toolchain(
    name = "qnx_cc_toolchain",
    toolchain = "@local_config_cc//:cc-compiler-qnx_x64",
    toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
)
  EOF
  cat << EOF > "$cpp_qnx_toolchain/WORKSPACE"
workspace(name = "cpp_qnx")
  EOF
fi

if [ ! -d "$buildbase_qnx_toolchain" ]; then
  mkdir -p "$buildbase_qnx_toolchain"
  cat << EOF > "$buildbase_qnx_toolchain/BUILD.bazel"
load("@rules_foreign_cc//toolchains/native_tools:native_tools_toolchain.bzl", "native_tool_toolchain")

toolchain(
    name = "qnx_cmake_toolchain",
    toolchain = ":qnx_cmake",
    toolchain_type = "@rules_foreign_cc//toolchains:cmake_toolchain",
)

toolchain(
    name = "qnx_ninja_toolchain",
    toolchain = ":qnx_ninja",
    toolchain_type = "@rules_foreign_cc//toolchains:ninja_toolchain",
)

native_tool_toolchain(
    name = "qnx_cmake",
    env = {"CMAKE": "/usr/bin/cmake3.5"},
    path = "/usr/bin/cmake3.5",
)

native_tool_toolchain(
    name = "qnx_ninja",
    env = {"NINJA": "/usr/bin/ninja"},
    path = "/usr/bin/ninja",
)
  EOF
  cat << EOF > "$buildbase_qnx_toolchain/WORKSPACE"
workspace(name = "buildbase_qnx")
  EOF
fi

declare -a default_bazel_flags=(build -c opt --define MEDIAPIPE_DISABLE_GPU=1)
declare -a qnx_bazel_flags=(--action_env=PYTHON_BIN_PATH=/usr/bin/python3 --repo_env=BAZEL_CXXOPTS=-std=c++17 --override_repository=python=./python --override_repository=python_qnx=./python_qnx --extra_toolchains=@python_qnx//:qnx_py_toolchain --extra_toolchains=@python_qnx//:qnx_py_toolchain2 --extra_toolchains=@python_qnx//:qnx_py_cc_toolchain --extra_toolchains=//cpp_qnx:qnx_cc_toolchain --extra_toolchains=//buildbase_qnx:qnx_cmake_toolchain --extra_toolchains=//buildbase_qnx:qnx_ninja_toolchain)

while [[ -n $1 ]]; do
  case $1 in
    -d)
      shift
      out_dir=$1
      ;;
    -c)
      shift
      clean
      ;;
    *)
      echo "Unsupported input argument $1."
      exit 1
      ;;
  esac
  shift
done

echo "app_dir: $app_dir"
echo "out_dir: $out_dir"

declare -a bazel_flags

apps="${app_dir}/*"
for app in ${apps}; do
  if [[ -d "${app}" ]]; then
    target_name=${app##*/}
    if [[ "${target_name}" == "autoflip" ||
          "${target_name}" == "hello_world" ||
          "${target_name}" == "media_sequence" ||
          "${target_name}" == "object_detection_3d" ||
          "${target_name}" == "template_matching" ]]; then
      continue
    fi
    target="${app}:${target_name}_cpu"

    echo "=== Target: ${target}"

    bazel_flags=("${default_bazel_flags[@]}")
    bazel_flags+=("${qnx_bazel_flags[@]}")
    bazel_flags+=(${target})

    bazel "${bazel_flags[@]}"
    cp -f "${bin_dir}/${app}/"*"_cpu" "${out_dir}"
  fi
done
